name: 16 - Working with Environments
run-name: 16 - Working with Environments | env - ${{ inputs.target-env }}
on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        description: 'Select the target environment for deployment'
        default: staging 

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    env:
      my_env_value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    
    steps:
      - name: Echo vars
        run: |
          echo "Env variable: ${{ env.my_env_value }}"
